language: python
python:
  - "3.7"
before_install:
  - python --version
  - pip install -U pip

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m unittest